### ISSUE TITLE
Extension not working in Burp 2021

### ISSUE THREAD

**Issue by Rackme** [LogicalTrust/BurpHttpMock#4]
Using Burp 2021.8.2, I am not able to mock any request.

![screenshot_3312](https://user-images.githubusercontent.com/13887304/132651720-57c3d17e-49ce-4edf-9b81-082a59fa9a03.png)

![screenshot_3309](https://user-images.githubusercontent.com/13887304/132651646-021f8bfb-a938-4b18-82ce-f4854a69ac7f.png)

Not further error in the Burp extension tab : 
![screenshot_3311](https://user-images.githubusercontent.com/13887304/132651621-38e44e75-41dc-4c0b-863b-5b5579e6edd8.png)

Is there any way to have a verbose debug  to understand what is happening ?

**Comment by mmmds** [comment]
Hi, I can't give you any solution at this moment, but I reproduced the issue and will look into it.

**Comment by Rackme** [comment]
@mmmds Yes exactly, I'm using the macos install, not the jar. I did not expect this could be an issue with extensions (could by like a portswigger "sandbox" ?).

Thanks for the workaround !

**Comment by mmmds** [comment]
The bug is fixed in the 1.1.7 version available in the BApp Store  - https://portswigger.net/bappstore/42680f96fc214513bc5211b3f25fd98b
