### ISSUE TITLE
Mock rules don't distinguish between HTTP methods

### ISSUE THREAD

**Issue by BayshaCZ** [LogicalTrust/BurpHttpMock#5]
Currently it's only possible to set mock rules based on the request URL. It would be very useful to be able to set up different responses for different HTTP methods on the same URL.
BTW, your extension is great, thanks a million for your work!

**Comment by mmmds** [comment]
Hi @BayshaCZ, thank you, that's a good suggestion. It shouldn't be that much code to write, so I'll try to do it in a month.

**Comment by mmmds** [comment]
The feature is implemented in the newest version: https://github.com/LogicalTrust/BurpHttpMock/releases/tag/1.1.4
@BayshaCZ, feel free to use the jar directly from GitHub. I will also submit an update to BApp Store.

**Comment by BayshaCZ** [comment]
I love you! <3 
This is incredible. Thank you so much!

**Comment by mmmds** [comment]
The feature is available in the 1.1.7 version in BApp Store - https://portswigger.net/bappstore/42680f96fc214513bc5211b3f25fd98b
