### ISSUE TITLE
How to mock (load in the response) binary files

### ISSUE THREAD

**Issue by LaiKash** [LogicalTrust/BurpHttpMock#6]
Hi!

This is not in fact an issue, I think. How can I insert a binary file (for example, an image) in the mocked response? The image could have code (steganography). Is there an option to load a file in the response?

Thanks!

**Comment by mmmds** [comment]
Hi @LaiKash , you can use "File contents" mock type to achieve it. First, you need to create a file with a full HTTP response with an image (or any other file).
```
filename="image.png"
echo -n -e "HTTP/1.1 200 OK\r\nContent-type: image/png\r\nContent-length: $(stat --printf=%s $filename)\r\n\r\n" > /tmp/response.txt
cat $filename >> /tmp/response.txt
```
Then, you need to modify the mock rule by
- changing its type from Basic to File contents,
- removing everything from the Response editor and placing a path (quoted) to the response file `"/tmp/response.txt"` (remember about Save button).

**Comment by mmmds** [comment]
Readme updated to my best knowledge at this moment.
